### PR TITLE
Revise dscquery to address Issue #182, implemented new function dscread

### PR DESCRIPTION
**Pull request by pcarbo**

### CODE REVIEW

**Comment by stephens999** [comment]
i'm wondering about dsc_read instead of dscread...
as a general convention i like dsc_ better than without _

**Comment by pcarbo** [comment]
@stephens999 We already have `dscquery` and `dscreval`. If you feel strongly, we could change the names of all the functions to `dsc_`.

**Comment by stephens999** [comment]
well it would be good to be consistent, and i would indeed support this
change.
(we could continue to include the old functions for backward compatibility)

**Comment by pcarbo** [comment]
@gaow If you are okay with this change, I will incorporate it into the Pull Request.

**Comment by pcarbo** [comment]
When this pull request is merged, we will be able to close Issue #180 and Issue #182.

**Pull request merged**
