### PR TITLE
Setup Circleci

### PR DESCRIPTION
**Pull request by jdblischak**
I setup CI testing on CircleCI. Currently the dscrutils tests are passing but the DSC tests are failing (error message below). Any ideas what is causing this issue?

https://circleci.com/gh/jdblischak/dsc/17

```
.WARNING: R library remotes is not available.
................
----------------------------------------------------------------------
Ran 17 tests in 6.304s

OK
.F
======================================================================
FAIL: testSyntaxPass (__main__.TestQuery)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_query.py", line 119, in testSyntaxPass
    self.assertEqual(observed, expected)
AssertionError: Lists differ: ['DSC[280 chars],0.0,NA,NA,NA,NA,gamma_lfsr,gamma_lfsr/simulat[828 chars],NA'] != ['DSC[280 chars],0.0,gamma_ci,gamma_ci/simulate_1_cause_grid_a[1200 chars]r_1']

First differing element 2:
'1,0.0,NA,NA,NA,NA,gamma_lfsr,gamma_lfsr/simulat[31 chars]sr_1'
'1,0.0,gamma_ci,gamma_ci/simulate_1_cause_grid_a[119 chars]A,NA'

Diff is 2474 characters long. Set self.maxDiff to None to see it.

----------------------------------------------------------------------
Ran 2 tests in 0.434s

FAILED (failures=1)
Exited with code 1
```

### CODE REVIEW

**Comment by gaow** [comment]
@jdblischak Thank you! I'm going to take a look after wrapping up something at hand. We are in the middle of re-considering "target" behavior and it again impacts the interface dealing with missing query results (likely a change introduce today that I was too hurry to run a test!)

**Comment by gaow** [comment]
@jdblischak I'm looking at this. All tests pass offline though ... still digging.

**Comment by jdblischak** [comment]
@gaow Note that you can test this directly in a local Docker container by using `ubuntu:bionic` and then running the steps in the configuration file. I suspect that some common system library (e.g. that is installed on your Linux system) must be missing from this Docker image.

**Comment by gaow** [comment]
@jdblischak what should we do with this PR? Do you want to activate the check another time see how it works? Notice that now we need to additionally install `r-data.table` from `conda` due to a recent change made to `dscrutils` (you need to include it in the CI configuration)

**Comment by jdblischak** [comment]
@gaow I rebased the PR onto master and force pushed. The R package data.table should be automatically installed because `devtools::install_deps()` installs all the packages listed in `DESCRIPTION`. Note that I am not using conda packages for this build.

https://circleci.com/gh/jdblischak/dsc/25

**Comment by gaow** [comment]
Thanks a lot @jdblischak this works perfectly now.

**Comment by jdblischak** [comment]
@gaow The build is still failing on my fork:

https://circleci.com/gh/jdblischak/dsc/26

Could you activate the build for the main repo:

https://circleci.com/add-projects/gh/stephenslab

**Comment by gaow** [comment]
@jdblischak built for the main repo; also failed. Will look into it ...

**Pull request merged**
